### PR TITLE
Prometheus annotations

### PR DESCRIPTION
**Pull request by ericvaandering**
Enables pod labels and sets up automatic scraping by prometheus in k8s for pods which produce prometheus metrics

### CODE REVIEW

**Comment by ericvaandering** [comment]
@tbeerman this is what we're doing for prometheus. By adding these annotations to pods, prometheus automatically finds the pods with exposed metrics and scrapes them.

**Comment by tbeerman** [comment]
Thanks @ericvaandering
I'm just wondering which metrics you try to expose here? Do you have some additional pod metrics that are not part of the upstream rucio container images or do you just your own prometheus servers? I'm just asking because in our ATLAS cluster we already get the Rucio metrics, like the conveyor submission rate and reaper deletion rate, by just setting this in our helm charts for the daemons:
```
    monitoring:
      enabled: true
      exporterPort: 8080
      targetPort: 8080
      interval: 30s
      telemetryPath: /metrics
      namespace: monitoring
      labels:
        release: prometheus-operator
...
  config:
      monitor:
        enable_metrics: "True"
```

This works for us ootb on the CERN provided clusters with v1.18 and `--labels monitoring_enabled=true`.

Anyway, I like the additional pod labels. Wouldn't it make sense to also make the annotations configurable like this in the values.yaml instead of hard-coding them? You can then still set the prometheus annotations in the default values.yaml but it would make it easier if you later need to change something.

I don't really understand why you need to add `serviceMonitorEnabled`. It doesn't seem to do anything.

**Comment by ericvaandering** [comment]
Well, I did install my own prometheus and this patch is all about the auto discovery, not the prometheus server running inside the daemon. So I gather this is how you are supposed to do this with a standard prometheus install into your cluster, not the cern enabled configuration. How does the CERN provided prometheus know which pods to fetch /metrics from?

We could do the annotations generically rather than specifically, yes. 

Finally I added the service monitor value specifically so that I could turn it off. It’s been a while, but with my setup it must have been causing a conflict.

**Comment by tbeerman** [comment]
Prometheus knows about where to scrape the metrics from the ServiceMonitor that will be installed when you set `monitoring.enabled: true`. It looks something like this:

```
metadata:
...
  labels:
    release: prometheus-operator
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    targetPort: 8080
  jobLabel: daemonprod-rucio-daemons-prometheus-exporter
  namespaceSelector:
    matchNames:
    - rucio
  selector:
    matchLabels:
      app: rucio-daemons
      release: daemonprod
```

It has to have the `release: prometheus-operator` label set. But then it should work.

But if adding the pod labels and annotations is necessary that's fine. It won't hurt in our ATLAS deployment and might also help others when they have a Prometheus installation similar to yours. So if you could just adapt the annotations I'll merge it.

**Comment by ericvaandering** [comment]
@tbeerman I've made the annotations generic now instead of prometheus centric. We can add the prometheus centric ones in our own files.

I did keep the servicemonitor piece because, like I said, I have to turn it off with my own installed prometheus instead of the CERN one. 

Please merge if you are good with this.

**Pull request merged**
