### PR TITLE
Add a helm chart for rucio/probes, some of which now work.

### PR DESCRIPTION
**Pull request by ericvaandering**
Currently they are all run every 15 minutes, but the groundwork is laid to run them on different intervals simply by adding new cron jobs

### CODE REVIEW

**Comment by ericvaandering** [comment]
@tbeerman This now works for the 8 probes CMS is using. 

I can't say I'm totally happy with the verbosity of the probe specification. Do you have a better idea?

I do want to preserve the ability to keep a different interval for various probes.

Don't merge this. If nothing else I want to clean it up. There might be some CMS specific stuff in there too that I want to get rid of.

**Comment by tbeerman** [comment]
You could just use a loop:

In values.yaml
```
probes:
  check_fts_backlog:
    enabled: true
    interval: 1
    onError: Continue
  check_messages_to_submit:
    enabled: false
    interval: 1
    onError: Continue
```

and jobber-configmap.yaml:

```
    jobs:
{{- range $probe, $config := .Values.probes }}
{{ if $config.enabled }}
      {{ $probe }}:
        cmd: /probes/common/{{ $probe }}
        time: 'R */{{ $config.interval }} * * * *'
        onError: {{ $config.onError }}
{{- end }}
{{- end }}
```

Not sure if `enabled` is necessary though. If you want to disable the probe you could also just comment it.

**Comment by ericvaandering** [comment]
OK. Yeah, as long as snake case parameters are OK, that's kind of what I was thinking too. I think I can keep the same setup with interval. You can turn something off by setting that to 0. No need for enabled.

**Comment by ericvaandering** [comment]
@tbeerman this looks much better and works fine.

Please merge when you approve.

**Comment by tbeerman** [comment]
Looks good but please change the default repository and tag to `rucio/probes` and `latest`

**Comment by ericvaandering** [comment]
Done. Please merge.

**Pull request merged**
